---
- name: "ğŸ’³ [Chaos 1] ê²°ì œ(paymentservice) Pod ê°•ì œ ì¢…ë£Œ"
  shell: |
    kubectl delete pod -n {{ target_namespace }} -l app=paymentservice --force --grace-period=0
  register: kill_pay_result

- name: "ê²°ì œ ì„œë¹„ìŠ¤ Pod ì‚­ì œ ê²°ê³¼ í™•ì¸"
  debug:
    msg: "Paymentservice Pod deleted. Output: {{ kill_pay_result.stdout }}"
